separator = " âˆ£ "

[matching]
cantata = "ï€"
copyq = "ïƒª"
VencordDesktop = "ï¡¨"
"org.kde.dolphin" = "ï¼"
"foobar2000.exe" = "î®"
"Gimp-2.10" = "ï‡¼"
gnome-calculator = "ï—«"
Google-chrome = "ï‰¨"
chromium = "ï‰¨"
kitty = "ï„ "
MEGAsync = "ğŒ"
"mp3tag.exe" = "ï€¬"
mpv = "ï¢€"
"com.obsproject.Studio" = "ï‡ˆ"
OnlyOffice = "ïœ«"
okular = "ïœ¤"
"io.github.tdesktop_x64.TDesktop" = "ï‹†"
Thunderbird = "ïƒ "
zoom = "ï¡ª"
WhatsApp = "ïˆ²"
wps = "ïœ«"
wpp = "ïœ¦"
"com.gitee.gmg137.NeteaseCloudMusicGtk4" = "ó°«”"
genymotion = "îœ"
"org.keepassxc.KeePassXC" = "î¬‘"
