separator = " âˆ£ "

[matching]
cantata = "ï€"
copyq = "ïƒª"
vesktop = "ó°™¯"
"org.kde.dolphin" = "ï¼"
"foobar2000.exe" = "î®"
"Gimp-2.10" = "ï‡¼"
"gimp" = "ï‡¼"
gnome-calculator = "ï‡¬"
Google-chrome = "ï‰¨"
chromium = "ï‰¨"
kitty = "ï„ "
librewolf = "î™˜"
MEGAsync = "ğŒ"
"mp3tag.exe" = "ï€¬"
mpv = "îšŸ"
"com.obsproject.Studio" = "ï‡ˆ"
OnlyOffice = "ğŸ–º"
"org.kde.okular" = "ï‡"
"io.github.tdesktop_x64.TDesktop" = "ï‹†"
"io.github.kukuruzka165.materialgram" = "ï‹†"
Thunderbird = "ïƒ "
vim = "î˜«"
WhatsApp = "ïˆ²"
"com.gitee.gmg137.NeteaseCloudMusicGtk4" = "ó°«”"
genymotion = "îœ"
"org.keepassxc.KeePassXC" = "î¬‘"
"org.bunkus.mkvtoolnix-gui" = "ó°•©"
Anydesk = "î¬º"
zoom = "ï€½"
"libreoffice-writer" = "ó°ˆ¬"
