[icons]
burp-StartBurp = "ğŸ•¶"
BurpBrowser = "ï’ˆ"
cantata = "ï€"
copyq = "ïƒª"
Discord = "ï¡¨"
dolphin = "ï¼"
Foobar2000 = "î®"
gimp = "ï‡¼"
gnome-calculator = "ï—«"
iBroadcast = "ï¢ƒ"
Google-chrome = "ï‰¨"
chromium = "ï‰¨"
kitty = "ï„ "
kotatogram = "î˜"
megasync = "ğŒ"
mp3tag = "ï€¬"
mpv = "ï¢€"
obs = "ï‡ˆ"
OnlyOffice = "ïœ«"
okular = "ïœ¤"
Pharo = "ï™²"
Plex = "ï™«"
qbittorrent = "ï€™"
ripcord = "ï¡¨"
Telegram = "ï‹†"
Thunderbird = "ïƒ "
zoom = "ï¡ª"
WhatsApp = "ïˆ²"
wps = "ïœ«"
wpp = "ïœ¦"

[aliases]
TelegramDesktop = "Telegram"
telegram-desktop = "Telegram"
"foobar2000.exe" = "Foobar2000"
"mp3tag.exe" = "mp3tag"
"zoom " = "zoom"
crx_magkoliahgffibhgfkmoealggombgknl = "Discord"
crx_aecmdlldeiiejaepipodjjekmbhjnpkb = "iBroadcast"
crx_nlckacehbpjmdkodiahlegjkfgjmmoim = "Plex"
crx_hnpfjngllnobngcgfapefoaidbinmjnm = "WhatsApp"
DesktopEditors = "OnlyOffice"
browser = "BurpBrowser"

[general]
separator = " â§¸ "
wm_property = "instance"

[options]
remove_duplicates = false
no_names = false
no_icon_names = true

